modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
[[mods]]
modId="hearthwell"
version="${file.jarVersion}"
displayName="Hearth Well"
logoFile="hearthwell.png"
credits="Thanks for this example mod goes to Java"
authors="Love, Cheese and small house plants"

description='''
A magitech mod about the old gods
'''

[[dependencies.hearthwell]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.hearthwell]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
